version: '3.8'

services:
  app:
    build: stock-sage
    container_name: stocksage-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/stocksage
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    volumes:
      - ./uploads:/app/uploads
    networks:
      - stocksage-network
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    container_name: stocksage-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=stocksage
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
    networks:
      - stocksage-network
    restart: unless-stopped

volumes:
  postgres-data:

networks:
  stocksage-network:
    driver: bridge
